# Use an official Node.js image as the base
FROM node:22

# Install dependencies for native modules
RUN apt-get update && apt-get install -y python3 g++ make

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install backend dependencies inside the container
RUN npm install

# Copy the backend source code to the container
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]
